# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7284bb7b826d53e5bd0c4688bf0739f655eba8ec1b4f25f79b2069a29fc4eb7d750a4a9c5ff0910cc52fe949e4a72950da387033d34b3a82b76e48848a8dfadc

test:
  secret_key_base: f3d084d4415ce3d005be73fa8e52f31ab97e2684ba4eeb26d98e9cdcac641cd1f655f5535db1349f96d2966e5d425df4d36002fb47b5ef01437d6d33522bd6c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
